---
  # Configuring httpd.conf and sending sample file
  - name: httpd.conf file
    copy: src=httpd.conf dest=/etc/httpd/conf/httpd.conf
    notify:
      restart apahe service

  - name: send index.html
    copy: scr=index.html dest=/var/www/html/index.html
  
