---
# download and install aws inspector
- name: download AWS inspector
  get_url:
    url: "{{ install_script_url }}"
    dest: "/tmp/aws-inspector-agent-install"

- name: run installer
  command: bash /tmp/aws-inspector-agent-install
