---
# tasks file for mediapeers.aws-inspector

#- name: Make sure system dependencies are met (libcurl3)
#  yum:
#    name: libcurl
#    state: present

- name: Download aws inspector agent installation script
  get_url:
    url: '{{ aws_inspector_installer_url }}'
    dest: /tmp/install

- name: Execute the agent installer
  become: yes
  become_user: root
  shell: bash /tmp/install

- name: Enable awsagent on bootup
  service:
    name: awsagent
    enabled: yes

- name: Get agent status
  become: yes
  become_user: root
  shell: '/opt/aws/awsagent/bin/awsagent status'
  register: aws_agent_status

- name: Output awsagent status
  debug:
    var: aws_agent_status.stdout

- name: Cleanup install script
  file:
    name: /tmp/install
    state: absent
