---
# Installing httpd package

- name: Launch AWS RHEL 7.3 Server
  become: yes
  become_user: root
  ec2:
    key_name: id_rsa
    state: present
    instance_type: t2.micro
    image: ami-f1978897
    count: 1
    vpc_subnet_id: subnet-bd1b96e4
    group: ansible_tutorial
    region: eu-west-1
    instance_tags: {"type":"apache"}
    assign_public_ip: yes
    wait: yes

# Added
  register: ec2_info

- debug: var=ec2_info
- debug: var=item
  with_items: ec2_info.instance_ids

- add_host: hostname={{ item.public_ip }} groupname={{ app_name }}_{{ server_env }}
  with_items: ec2_info.instances

- name: wait for instances to listen on port:22
  wait_for:
    state: started
    host: "{{ item.public_dns_name }}"
    port: 22
  with_items: ec2_info.instances
